spring:
  datasource:
    url: jdbc:mysql://localhost:3306/domiciliation
    username: root
    password:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true